# version: "3.8"

services:
  nginx-proxy:
    build:
      context: .
      dockerfile: Dockerfile.nginx-certbot
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
      - "8083:8083"
      - "88:88"
      - "83:83"
      - "89:89"
      - "8089:8089"
      - "90:90"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./conf.d:/etc/nginx/conf.d
      - ./snippets:/etc/nginx/snippets
      - ./html:/var/www/html
    networks:
      - proxy-net
    restart: always

networks:
  proxy-net:
    external: true